### ISSUE TITLE
Freetype installation issues

### ISSUE THREAD

**Issue by petulla** [mapnik/mapnik#3211] opened 2015-12-24 01:12 UTC
I know there are a few threads on this but I haven't been able to successfully solve mine. So hoping to get some help here.

Despite efforts to symlink my way out of trouble, I cannot get Mapnik to find Freetype.

```
-I/usr/include src/font_engine_freetype.cpp
In file included from src/font_engine_freetype.cpp:27:
include/mapnik/text/face.hpp:34:10: fatal error: 'freetype.h'
      file not found
#include FT_FREETYPE_H
         ^
/usr/include/config/ftheader.h:173:24: note: expanded from
      macro 'FT_FREETYPE_H'
#define FT_FREETYPE_H  <freetype.h>
                       ^
1 error generated.
scons: *** [src/font_engine_freetype.os] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2
```

Freetype is installed with brew so `freetype-config --cflags` returns `-I/opt/local/include/freetype2`

I've symlinked to `/usr/include/` so `sudo ln -s /opt/local/include/freetype2/fttypes.h /usr/include/` returns 
`ln: /usr/include//fttypes.h: File exists`

I'm sure the solution is easy here but unix symlinking isn't my strong suit..

**Comment by lightmare** [comment] 2018-07-17 17:55
If mapnik build script fails to obtain proper flags from `pkg-config` or `freetype-config`, they can be overridden with `./configure FREETYPE_INCLUDES=/path/to/include FREETYPE_LIBS=/path/to/lib`.

Closing as the issue is old. Feel free to reopen if problem persists.

**Closed by lightmare** 2018-07-17 17:55 UTC
