### ISSUE TITLE
Some images broken with PNG hextree

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik#1987] opened 2013-08-20 17:03 UTC
Found that Mapnik produces broken tiles with `png8:m=h` option enabled in certain cases. Illustrations are better than words.
1 octree:
![_3o](https://f.cloud.github.com/assets/1121499/995085/9ba5805c-09b7-11e3-8bd4-9278b7fc47a8.png)
1 hextree:
![_3h](https://f.cloud.github.com/assets/1121499/995087/a6ae6f2c-09b7-11e3-9cf9-4e32dee0a9aa.png)

2 octree:
![_2o](https://f.cloud.github.com/assets/1121499/995099/c9b2ec32-09b7-11e3-918c-e71037b355bc.png)
2 hextree:
![_2h](https://f.cloud.github.com/assets/1121499/995104/d0c95204-09b7-11e3-915f-63fd062d27bd.png)

3 octree:
![_1o](https://f.cloud.github.com/assets/1121499/995105/d68e3b46-09b7-11e3-84e0-e7c04aeef771.png)
3 hextree:
![_1h](https://f.cloud.github.com/assets/1121499/995107/dc3120c2-09b7-11e3-9505-7e51c736d4f5.png)

I'm aware of https://github.com/mapnik/mapnik/wiki/OutputFormats#hextree-details, but the results are worse that I expected. Actually, I want to use one option (`png8:m=h`) for all our maps.

**Comment by springmeyer** [comment] 2015-02-02 22:21
confirmed this is still present and is a dupe of #2292. Let's track at #2292.

**Closed by springmeyer** 2015-02-02 22:21 UTC
