### ISSUE TITLE
Mapnik master build failing on FreeBSD/PCBSD 10.1

### ISSUE THREAD

**Issue by PeterSprague** [mapnik/mapnik#2707] opened 2015-02-16 19:39 UTC
Follow-up on Tilemill -> node-mapnik install errors and issue report
https://github.com/mapnik/node-mapnik/issues/395

As per recommendation to build mapnik.master to avoid version mismatch:
pkg info mapnik => V2.2
pkg remove mapnik
cd /usr/local
git clone https://github.com/mapnik/mapnik.git
mv mapnik mapnik.git
cd /usr/local/mapnik.git
python scons/scons.py configure

error: 
Configuring build environment...
Configuring on FreeBSD in *release mode*...
Checking for freetype-config... yes
Checking for xml2-config... yes
Checking for dlfcn.h support ... no
Checking if compiler (g++) supports -std=c++11 flag... (cached) no
C++ compiler does not support C++11 standard (-std=c++11), which is required. Please upgrade your compiler to at least g++ 4.7 (ideally 4.8)

pkg info gcc => gcc-4.8.4
cd /usr/ports/lang/gcc5
make install clean

cd /usr/local/mapnik.git
git branch => master
python scons/scons.py configure
same error as above

???

**Comment by flippmoke** [comment] 2015-02-16 20:47
If you are on master for mapnik, you are using mapnik 3.x

**Comment by PeterSprague** [comment] 2015-02-16 21:21
Yes, that's the Mapnik version that is needed for node-mapnik 
Issue is that it will not "compile" under FreeBSD 10.1 for me

**Comment by springmeyer** [comment] 2015-02-16 21:30
@PeterSprague - please find the `config.log` that is dropped inside the mapnik folder after a failed configure (if you watch the configure output you will see the path to the config.log printed near the end). Can you post it to https://gist.github.com/? It will show why the `C++ compiler does not support C++11 standard ` check is failing. You may need to do `./configure CXX=/full/path/to/g++-4.8`. Or you could use `clang++` instead of g++.

**Comment by PeterSprague** [comment] 2015-02-16 22:45
Made public gist of run using absolute path to gcc
Note:  /etc/make.conf has been set with:
WITH_CLANG=yes
WITH_CLANG_EXTRAS=yes
WITH_CLANG_IS_CC=yes
WITHOUT_GCC=yes

ran: python scons/scons.py configure CXX=/usr/local/bin/gcc5 (also tried with clang)

Your suggestion to use full path is needed for clang or gcc, but when run boost, ... dependencies header files are not located.  All dependencies have been installed via pkg.

**Comment by springmeyer** [comment] 2015-02-16 23:10
@PeterSprague you'll need to share the link to the gist otherwise I cannot know what it contains.

> Your suggestion to use full path is needed for clang or gcc, but when run boost, ... dependencies header files are not located. All dependencies have been installed via pkg.

I think configuring against boost is a totally separate issue. You likely need to set `./configure BOOST_INCLUDES=/path/to/includes BOOST_LIBS=/path/lib/libs`

**Comment by PeterSprague** [comment] 2015-02-16 23:15
Its not just boost, and the files exist, just not found by configure

from console:
Exiting... the following required dependencies were not found:
   - z (Z compression library | more info: http://www.zlib.net/)
   - icuuc (ICU C++ library | configure with ICU_LIBS & ICU_INCLUDES or use ICU_LIB_NAME to specify custom lib name  | more info: http://site.icu-project.org/)
   - harfbuzz-min-version (HarfBuzz >= 0.9.34 (required for font-feature-settings support))
   - boost system (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)
   - boost filesystem (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)
   - boost regex (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)
   - boost thread (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)

See '/usr/local/mapnik.git/config.log' for details on possible problems.

I could build a config.py with paths, but there must be something else causing this that could be fixed.

**Comment by PeterSprague** [comment] 2015-02-17 16:20
Morning thoughts (fishing?):
Current $PATH works well for other port compiles, even Mapnik 2.2 when built
Python works well with MapProxy (not a build, but finds all needed files)
Am i missing something explicit in my Python 2.7 config?
Should I install and try Python 3?

**Comment by springmeyer** [comment] 2015-02-17 17:29
The problem is that your compiler `gcc55` is not finding an appropriate c++ library. This is a fundamental setup problem on your machine and your setup will not be able to compile and link even the most trivial C++ application until you fix this. The reason the Mapnik configure is failing is that all C++ dependencies cannot be found because the compiler is broken:

```
conftest_10.cpp:(.text+0x1b): undefined reference to `std::cout'
```

```
/usr/local/bin/ld: .sconf_temp/conftest_12.o: undefined reference to symbol '_ZNKSt13runtime_error4whatEv'
//usr/lib/libc++.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Overall I think the issue is that you are using gcc but it is not automatically using libc++ for its c++ library. You may be able to work around the problem by doing:

```
./configure CUSTOM_LDFLAGS="-stdlib=libc++"
```

What I recommend doing however is debugging this outside of Mapnik - since it has nothing to do with Mapnik. Instead create a simple C++ program and make sure you can get it running with your chosen compiler:

```
echo '#include <iostream>' > test.cpp
echo 'int main() { std::clog << "works\n";return 0; }' >> test.cpp
clang++ -o test-program test.cpp -std=c++11
./test-program
```

That should print `works`. For you if you use `gcc55` it will likely break. This may be because `gcc55` is the C compiler and not the C++ compiler, so try using clang++ or g++55 (or something like that).

**Comment by PeterSprague** [comment] 2015-02-17 17:56
Thanks.
Get same error(s) with clang-3.5
See gist: https://gist.github.com/PeterSprague/6d2b8b73b2ac6a7e408d

Will debug as you suggested.

**Comment by springmeyer** [comment] 2015-02-17 17:57
clang-3.5 and gcc55 are C compilers, you need the C++ compiler, aka clang++-3.5 or g++-55.

**Comment by PeterSprague** [comment] 2015-02-17 18:05
debug program works, so clang++ is being used.
Not to be too much of a noob, but how do i now implement with Mapnik build in Python?
BTW: workaround does work.

**Comment by springmeyer** [comment] 2015-02-17 18:07
I'm going to close this issue since the problem is unrelated to Mapnik and not a bug. Please open new issues at https://github.com/mapnik/mapnik-support for specific questions you might have.

**Closed by springmeyer** 2015-02-17 18:07 UTC
