### ISSUE TITLE
filter starting with "not"

### ISSUE THREAD

**Issue by mokarto** [mapnik/mapnik#3017] opened 2015-08-05 06:14 UTC
A filter starting with "not" will be ignored.

     <Style name="L.11_31000_2_PRI1_Fuellung_1307">
       <Rule>
          <MaxScaleDenominator>12000</MaxScaleDenominator>
          <MinScaleDenominator>6000</MinScaleDenominator>
          <Filter> (not [ftr_fahrbahntrennung] = '2000_getrennt' and [wdm_widmung] = '1307_Gemeindestrasse' and  [pri_prioritaet] = 1 and not [bdi_verkehrsb_inneroert] = '2002_Anliegerverkehr' and  ([zus_zustand] = '1100_in_Betrieb' or not  [zus_zustand] = '1300_im_Bau') and not [fkt_funktion] ='1808_Fussgaengerzone') </Filter>
          <LineSymbolizer clip="false"  stroke="#fcfcfc" stroke-linecap="butt" stroke-linejoin="round" stroke-opacity="1" stroke-width="6.85" /></Rule>
      </Style>
    > 
All features of the resultset will be rendered with this style.

If I put "not [ftr_fahrbahntrennung] = '2000_getrennt'" e.g. at the of the filter term the filter works as expected.

Mapnik is running on different machines:
* 2.2. windows: ok
* 2.1. Ubuntu 14.04: ok
* 3.0.rc1 Ubuntu 14.04: ignoring the filter
* 3.0.rc2 Ubuntu14.04: ignoring the filter
* 3.0.2 Ubuntu 14.04: testing

**Comment by mboeringa** [comment] 2015-08-05 20:29
I think you need to review your filter statements carefully, and add required brackets where needed, like for the NOT statement. I would also be carefully not to overuse the NOT operator, it can get confusing and contradictory quickly.

E.g., I am not sure what you try to achieve with the:

**([zus_zustand] = '1100_in_Betrieb' or not  [zus_zustand] = '1300_im_Bau')**

clause. 

The

**or not  [zus_zustand] = '1300_im_Bau'**

clause will select everything in the **[zus_zustand]** field except **'1300_im_Bau'**. This means it will include the **'1100_in_Betrieb'** value and hence the OR operator and everything before it has no function in this part of the clause.

**Comment by mokarto** [comment] 2015-08-06 10:44
Sorry for the bad example.
I have simplified the term.

My PostGIS statement is:

    select geoloc, ksn_kartensignaturnummer, pri_prioritaet from geoinfo7_strassen_ksn_pri where ksn_kartensignaturnummer in(3010,3040,3050,3060,3070,3080,3090,3100,3120,3130,3140,3150,3160,3170,3175,3171,3176,3180,3185,3181,3190,3194,3196,3199,3200,3201,3202,3232,3205,3206,3207,3208,3209,3210,3215,3216,3220,3221,3235,3236,3237,3238)) as strassen_0

The result are 2,137,068 items.

The style-filter is very simple basing on a number (ksn_kartensignaturnummer) of the line symbol. '3010' is a mainroad with orange filling. Each kind of a street has its own number (main road, secondary road, .., path, ...).

    	<Style name="3010_F">
    ...
    		<Rule>
    			<MaxScaleDenominator>6400</MaxScaleDenominator>
    			<MinScaleDenominator>3200</MinScaleDenominator>
    			<Filter> [ksn_kartensignaturnummer] = 3010</Filter>
    			<LineSymbolizer clip="false"  stroke="#F27321" stroke-linecap="butt" stroke-linejoin="round" stroke-opacity="1" stroke-width="29.32" />
    		</Rule>
    ...
    	</Style>

![without_0005708](https://cloud.githubusercontent.com/assets/13654607/9109791/a4d906ca-3c38-11e5-83fa-ad388d7e7d25.png)

The result of the rendering process is the file "without_0005708.png".

Now I add a "not" clause at the beginning of the term.
* priority < 0: tunnel
* priority = 0: at ground level
* priority > 0: bridge

not ([pri_prioritaet] = 0) means all streets in a tunnel or on a bridge.
The filter should reduce the items to 55,533.  

     <Filter> not ([pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010</Filter>


But all items are rendered as a mainroad with orange filling. The filter works like the regular expression ' * ' (see starting_with_not_0005708.png).

![starting_with_not_0005708](https://cloud.githubusercontent.com/assets/13654607/9109794/afb0eca2-3c38-11e5-9945-b25854a01eb8.png)


thanks mokarto

**Comment by mboeringa** [comment] 2015-08-06 11:12
What happens is you adjust the filter to:

**<Filter> (not [pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010</Filter>**

so move the '(' before the not. I think the problem may be that otherwise everything following the not is interpreted as being part of the NOT clause, meaning the [pri_prioritaet] and [ksn_kartensignaturnummer] are both evaluated during processing of the NOT clause, like if it were:

**<Filter> not ([pri_prioritaet] = 0 and [ksn_kartensignaturnummer] = 3010)</Filter>**

Since the **[ksn_kartensignaturnummer] = 3010** *may* not be associated with in any ground level street in your case, the **([pri_prioritaet] = 0 and [ksn_kartensignaturnummer] = 3010)** clause effectively selects nothing. Since the opposite (NOT) of no records is ALL other records, it selects all the roads.

**Comment by mokarto** [comment] 2015-08-06 12:55
I can confirm your guess.

Not working are:
* <Filter> not ([pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010</Filter>
* <Filter> not [pri_prioritaet] = 0 and [ksn_kartensignaturnummer] = 3010</Filter>

Correct working are:
* <Filter> (not [pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010</Filter>
* <Filter> [ksn_kartensignaturnummer] = 3010 and not [pri_prioritaet] = 0 </Filter>

If you put a NOT clause at the beginning of a term you have to bracket the whole (not [pri_prioritaet] = 0) otherwise not.
There is a change of the interpreter from mapnik 2.2. to 3.0.

My memory hook will be: Think positiv first!

**Comment by mboeringa** [comment] 2015-08-06 13:40
Good it was of help. This is basic SQL logic, once you get used to it, it becomes easier. Nonetheless, you always need to be extremely careful with the bracketing and AND/OR/NOT operators. It is so easy to get it wrong.

**Comment by springmeyer** [comment] 2015-08-07 23:57
@mokarto - if you think this is an unwanted regression/bug, then we'll need a reduced testcase demonstrating the problem. See https://github.com/mapnik/mapnik/wiki/A-perfect-testcase

**Comment by mboeringa** [comment] 2015-08-08 15:13
> @mokarto - **if you think this is an unwanted regression/bug**, then we'll need a reduced testcase demonstrating the problem. See https://github.com/mapnik/mapnik/wiki/A-perfect-testcase

Personally, if this is indeed the case, I consider this an improvement, as it now seems a more stringent and logical scheme, most likely compliant with SQL standards, is followed and enforced, whereas in previous versions, potentially unpredictable and ambiguous filter statements could be written regarding the use of NOT.

I mean, how would a filter statement like:

**not ([pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010**

need to be interpreted logically if no brackets for the NOT operator are required?

As:
**not (([pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010)**
or:
**(not [pri_prioritaet] = 0) and [ksn_kartensignaturnummer] = 3010**

No one can tell really... (unless documented in Mapnik Help).

**Comment by mokarto** [comment] 2015-08-09 09:36
I have already fixed all filter terms in my stylesheets. Everything is ok for me. Maybe I'm the only pessimist starting with a NOT clause (I didn't find any statement in the OpenStreetMap Stylesheet).

Over the last years I put all SQL-statements from the stylesheets to the PostGIS to speed up the rendering process. These statements are part of an old stylesheed but still used in an application.

I would provide an indication for other users investigating a changed behaviour in 3.0.

If You want to analyse this case let me know. I will prepare a testcase.

Thank you for your contribution to our good work.
mokarto

**Comment by springmeyer** [comment] 2015-08-10 18:25
> If You want to analyse this case let me know. I will prepare a testcase.

Yes, if the behavior changed, it would be nice to have a very small testcase demonstrating this so we can then investigate if we think the change is intended.

**Comment by mokarto** [comment] 2015-08-11 19:59
I had udloaded a little testcase to dropbox: 
https://www.dropbox.com/sh/2yq3keax2mql2zg/AADOQ4j7T9ZMR47E8fwsVoPGa?dl=0

the testcase contains a
* shape file with few items: not_test.shp
* python script: not_test.py
* xml stylesheet: not_test.xml

The python script produces two pictues
* the scale 4513 is a very simple term asking for one value of the attribute "ksn_karten": **<Filter> [ksn_karten] = 3205</Filter>**
* the scale 4515 combines the first term starting with a not clause of the second attribute "pri_priori": **<Filter>not [pri_priori] = 0 and  [ksn_karten] = 3205</Filter>**. 
There are only two items with NOT = 0 (one with pri_priori = 1 an the other one with with pri_priori = -1).

My results are added:
* 0004513_windows_mapnik_v22.png
* 0004515_windows_mapnik_v22.png
* 0004513_ubuntu_mapnik_v30.png
* 0004515_ubuntu_mapnik_v30.png

**Comment by springmeyer** [comment] 2015-08-11 20:21
thank you for the testcase @mokarto - I've assigned this to @artemp to take a closer look for consideration if this needs fixed for the next release (or if not).

**Comment by artemp** [comment] 2015-08-12 09:13
@mboeringa  @mokarto - thanks for digging this and test case. I need find time to investigate this issue properly. 

Meanwhile, why not 

`[pri_priori] <> 0` 

instead of

`not [pri_priori] = 0`

?

**Comment by lightmare** [comment] 2015-12-27 02:40
Hi, I made a note at the problematic grammar line [here](https://github.com/mapnik/mapnik/blame/master/include/mapnik/expression_grammar_impl.hpp#L191).

You can add this to `test/unit/core/expresssions_test.cpp`:
```c++
// operator precedence
expr = mapnik::parse_expression("  not true  or true ") == true);
REQUIRE(evaluate(*feature, *expr) == true);
// ^ currently fails because evaled as "not (true or false)"

// with parentheses showing how it should be interpreted
expr = mapnik::parse_expression(" (not true) or true ") == true);
REQUIRE(evaluate(*feature, *expr) == true);
```

**Comment by springmeyer** [comment] 2016-02-25 00:17
Looks like tests for this landed in https://github.com/mapnik/mapnik/commit/ae39d48b861a10fdae62eb96226c65c5c46bc9bd such that the mention of new tests needed by @lightmare at https://github.com/mapnik/mapnik/issues/3017#issuecomment-167375961 is covered. So I will close, please re-open if we are missing anything.

**Closed** 2016-02-25 15:28 UTC
Labels: expressions
