### ISSUE TITLE
Shapeindex - skip `null` shapes 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3288] opened 2016-02-08 14:49 UTC
`null` shapes records don't have an extent element and should be skipped 
ref: https://github.com/mapbox/tilelive-bridge/issues/77

**Comment by springmeyer** [comment] 2016-02-08 21:35
Needs unit test before closing.

**Comment by artemp** [comment] 2016-02-09 10:47
script used to create 'null' shapes test data  via @BergWerkGIS 

```JavaScript
var gdal = require('gdal');

var wgs84 = gdal.SpatialReference.fromEPSG(4326);

/*******point ********/
var pnt_ds = gdal.open('pnts', 'w', 'ESRI Shapefile');
var pnt_lyr = pnt_ds.layers.create('pnts', wgs84, gdal.Point);

pnt_lyr.fields.add(new gdal.FieldDefn('desc', gdal.OFTString));

addFeature(pnt_lyr, new gdal.Point(50, 50), 'pnt @ 50/50');
addFeature(pnt_lyr, null, 'NULL geom');
addFeature(pnt_lyr, new gdal.Point(50, 100), 'pnt @ 50/100');

pnt_ds.flush();
pnt_ds.close();

/********polygon ********/
var poly_ds = gdal.open('plygns', 'w', 'ESRI Shapefile');
var poly_lyr = poly_ds.layers.create('plygns', wgs84, gdal.Polygon);

poly_lyr.fields.add(new gdal.FieldDefn('desc', gdal.OFTString));

var poly = createPolygon([20, 20, 35, 35]);
addFeature(poly_lyr, poly, '[20, 20, 35, 35]');

addFeature(poly_lyr, null, 'NULL geom');

poly = createPolygon([50, 50, 75, 75]);
addFeature(poly_lyr, poly, 'poly @ 50/50 - 75/75');

poly_ds.flush();
poly_ds.close();

function addFeature(lyr, geom, desc) {
    var feat = new gdal.Feature(lyr);
    feat.setGeometry(geom);
    feat.fields.set('desc', desc);
    lyr.features.add(feat);
    lyr.flush();
}

function createPolygon(coords) {
    var poly = new gdal.Polygon();
    var ring = new gdal.LinearRing();
    ring.points.add(coords[0], coords[1], 0);
    ring.points.add(coords[0], coords[3], 0);
    ring.points.add(coords[2], coords[3], 0);
    ring.points.add(coords[2], coords[1], 0);
    ring.points.add(coords[0], coords[1], 0);
    poly.rings.add(ring);
    return poly;
}
```

**Closed** 2016-02-09 10:48 UTC
Labels: bug, input.shape

**Comment by springmeyer** [comment] 2016-02-09 18:39
great job on testing @artemp @BergWerkGIS. I uncommented the fix and confirmed that the test is capturing the behavior since it failed with the fix commented:

```
-------------------------------------------------------------------------------
shapeindex
  Shapefile index
-------------------------------------------------------------------------------
test/unit/datasource/shapeindex.cpp:87
...............................................................................

test/unit/datasource/shapeindex.cpp:120: FAILED:
  REQUIRE( feature_count == feature_count_indexed )
with expansion:
  2 == 1
with messages:
  path := test/data/shp/point_null_point.shp
  index_parts := 0
```
