### ISSUE TITLE
label the text In the direction of the road and along the road

### ISSUE THREAD

**Issue by Lilyliu83** [mapnik/mapnik#3781] opened 2017-10-13 02:12 UTC
Hello,I want to know ,how can label the text In the direction of the road and along the road,like picture 1 not picture 2

![29711968-06f8e6f0-89ca-11e7-8e7b-575d10c7c2df](https://user-images.githubusercontent.com/28856322/31527326-f9c4b7ce-affe-11e7-829b-b37546dfbc4d.png)

picture 1 

<img width="122" alt="29711808-4a231b04-89c9-11e7-8012-c43cfe140662" src="https://user-images.githubusercontent.com/28856322/31527331-01ec2cb6-afff-11e7-8e15-099e8b1fe320.png">

picture 2

**Comment by lightmare** [comment] 2018-07-18 20:36
Duplicate of #3745

**Closed by lightmare** 2018-07-18 20:36 UTC
