### ISSUE TITLE
could not create BreakIterator: U_MISSING_RESOURCE_ERROR

### ISSUE THREAD

**Issue by bladepeter** [mapnik/mapnik#3193] opened 2015-12-02 05:23 UTC
when I use TextSymbolizer as following, if the text is too long ,mapnik report the "could not create BreakIterator: U_MISSING_RESOURCE_ERROR" ,so what can I do? @springmeyer 

 <Rule>
            <Filter>([id] = 'text-in-legend')</Filter>
            <TextSymbolizer face-name='Arial Unicode MS Regular' size='232.8059846658458' fill='rgb(68, 68, 68)' placement="line" allow-overlap='false'>[content]</TextSymbolizer>
        </Rule>

**Comment by nyurik** [comment] 2016-04-28 02:35
I suspect I am seeing the same issue (or at least the same error message). The tile rendering still happens though.

**Comment by springmeyer** [comment] 2016-04-28 16:21
This does not have to do with text that is too long. This error will happen when your build of ICU is broken such that the ICU data library cannot be built. Situations where this can happen include:

   - You've built ICU to load its data via a .dat file, but your environment setting for ICU_DATA is pointing to a location that does not contain the .dat file
   - You've built ICU to load its data via a .dat file and then have moved the ICU build to another machine and need to actually set ICU_DATA to point to the new location of the .dat file
  - You've built ICU to load its data via a shared library but something about the ICU build has broken - maybe the BreakIterator data was not included due to a build configuration issue or your program is linking duplicate ICU versions such that the data libraries are clobbering each other.

The take home is: this is not a Mapnik issue, but something that needs to be fixed by rebuilding ICU correctly, ensuring only one ICU library on your system, and then ensuring that both boost and mapnik are built correctly against that working ICU version.

**Closed by springmeyer** 2016-04-28 16:21 UTC

**Comment by springmeyer** [comment] 2016-04-28 16:24
@nyurik - if you are hitting this with a node-mapnik binary, then the problem is either I packaged the binaries with some problem or you are running node with ICU built in and it is clashing. Please create an issue at node-mapnik if this is the case. Note: the node-mapnik binaries bundle an ICU .dat inside `lib/binding` and create a `mapnik_settings.js` with ICU_DATA set to the relative path and then get that ICU_DATA environment set dynamically via https://github.com/mapnik/node-mapnik/blob/master/lib/mapnik.js#L13-L24

**Comment by nyurik** [comment] 2016-04-28 16:25
@springmeyer the build is fully automated for me during npm install (ubuntu 16.x). I will double check if this also happens when repo is built using docker in a clean env.  Thanks for the feedback!

**Comment by springmeyer** [comment] 2016-04-28 16:28
Okay, probably not related by cross referencing #3367 just in case it is.

**Comment by nyurik** [comment] 2016-04-28 18:24
@springmeyer I just ran some tests on the production servers, and I don't see those messages. So I guess when mapnik-node was built inside the docker (built for debian target), it worked without warnings. But the local build during npm install might have caused issues.  I might try to poke at it later, but all good so far.

**Comment by math1985** [comment] 2017-08-15 22:42
Confirmed: https://github.com/gravitystorm/openstreetmap-carto/issues/2755

**Comment by math1985** [comment] 2017-08-18 22:02
The official Docker from openstreetmap-carto can be used to reproduce this issue.

**Comment by kocio-pl** [comment] 2017-09-06 10:11
From my osm-carto tests it looks it might be a problem with proper ICU version. 

Looks like current npm Mapnik package uses libicu55 and for example Debian Stretch has libicu57, which makes a problem with breaking lines in labels, because ICU 57 is not backward compatible probably. In Ubuntu Xenial both libraries are available and the problem goes away, but Debian skipped ICU 55 entirely (in Jessie it was ICU 52), so I suspect there will be problems on this platform anyway.
