### ISSUE TITLE
Text conflicting with labels in 3.0 RC

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2917] opened 2015-06-16 20:19 UTC
openstreetmap-carto labels POIs in two passes, one to place the icon on the point itself, another to place the name with a text-dy.

This is, for some as yet unknown reason, not working with the offset 3.0.0 RC branch

2.2
![image](https://cloud.githubusercontent.com/assets/1190866/8193518/252a374a-142a-11e5-9506-799fd13ae34c.png)
3.0 RC
![image](https://cloud.githubusercontent.com/assets/1190866/8193520/2792dab4-142a-11e5-851e-c64ed952c1b0.png)

This could be text-dy related changes also showing up in #2913, as if the text-dy is wrong, the text will conflict with the icon for the same POI and not render.

This is a blocker for openstreetmap-carto and Mapnik 3.

**Comment by pnorman** [comment] 2015-06-16 20:22
I'm going to see if I can narrow this down somewhat and at least see if it's text-dy, but I wanted to get it in because it's an important issue.

**Comment by pnorman** [comment] 2015-06-16 20:49
So, there's a few things going on here. Firstly, the bboxes for label collisions are being handled differently, as debug mode indicates

2.2
![image](https://cloud.githubusercontent.com/assets/1190866/8193958/505dfef8-142d-11e5-8bc6-b45a019dcf35.png)

3.0 RC
![image](https://cloud.githubusercontent.com/assets/1190866/8193966/55047acc-142d-11e5-8a74-2378f85208d0.png)

This is not the cause of the bug as far as I can tell, but should be noted in the cartographer's notes (#2875)

What is being styled is either a point or an area, with MSS of approximately

```mss
.points {
  [feature = 'shop_other'][zoom >= 17] {
    marker-fill: @shop-icon;
    marker-width: 6;
    marker-line-width: 0;
    marker-placement: interior;
    marker-clip: false;
  }
.text {
  [feature = 'shop_other']{
    text-name: "[name]";
    text-size: 10;
    text-dy: 18;
    text-placement: interior;
  }
}
```
Both .points and .text are classes which have one layer for POINTs and another for POLYGONs. Removing `text-placement: interior;` from the text makes it render on 3.0, which makes me think this is a variation of #2863.

**Comment by flippmoke** [comment] 2015-06-17 00:23
@springmeyer assigned this to you because of the possible connection to #2863 if you want me to look into it please assign it back to me.

**Comment by springmeyer** [comment] 2015-06-24 06:23
@pnorman thanks for the report and the research. My first impression is that it is in fact due to the change in collision boxes you mention. The harfbuzz branch changed to using a single bbox for straight text even if angled. This can either be seen as a feature (better performance) or a regression. See the testcase linked off of #2207.

**Comment by pnorman** [comment] 2015-06-24 16:54
> @pnorman thanks for the report and the research. My first impression is that it is in fact due to the change in collision boxes you mention. The harfbuzz branch changed to using a single bbox for straight text even if angled. This can either be seen as a feature (better performance) or a regression. See the testcase linked off of #2207.

How does `text-placement: interior;` factor into that?

**Comment by springmeyer** [comment] 2015-06-24 16:56
@pnorman - yeah, woke up this morning with fresh eyes and I think I'm wrong - this is very likely (like you said) a `text-placement: interior;` bug. Will take a look later at replicating and fixing with this in mind.

**Comment by springmeyer** [comment] 2015-06-25 00:05
yes, this was a `text-placement:interior` regression: Basically this parameter worked in 2.3.x against points. In master it previously only worked against polygons. The support for points has been restored and when used against points is means the same thing as `text-placement:point`;

fixed in https://github.com/mapnik/mapnik/commit/5a032ee98be4daa3587110acd7a1aa61aaaffa6b

**Closed by springmeyer** 2015-06-25 00:05 UTC
