### ISSUE TITLE
which point、polyline、polygon on the   rendering map

### ISSUE THREAD

**Issue by Lilyliu83** [mapnik/mapnik#3686] opened 2017-05-26 02:20 UTC
Hello,I want to know ,which point、polyline、polygon on the rendering map,maybe first  I can  know,how get the value of all map features's gid  at a map level on map   after  map rendering.
Thank you for any help.

**Comment by der-stefan** [comment] 2017-08-08 20:26
Duplicate of #3691

**Comment by Lilyliu83** [comment] 2017-09-19 05:52
@der-stefan Thank you for help，I will try to know it.

**Closed** 2017-09-20 11:25 UTC
