### ISSUE TITLE
geojson parser does not handle `null` properties on features

### ISSUE THREAD

**Issue by jakepruitt** [mapnik/mapnik#4177] opened 2020-10-07 16:35 UTC
Per [the geojson spec](https://geojson.org/geojson-spec.html#feature-objects), the `properties` of a feature can be `null`. I tried parsing a geojson file with `null` properties but got the following error:

```
Error: boost::spirit::x3::expectation_failure
```

I imagine it's likely an issue with the boost parsing in [this file](https://github.com/mapnik/mapnik/blob/f104edbefbfab0d477bc15504c70c5c48631b694/include/mapnik/json/feature_grammar_x3_def.hpp), but my instincts might be wrong.

cc/ @artemp

**Comment by artemp** [comment] 2020-10-07 16:37
@jakepruitt - looks like regression, thanks

**Comment by artemp** [comment] 2020-10-12 09:46
Fixed in https://github.com/mapnik/mapnik/commit/7d1a559ae2f1bc6de1ec32b94a94f46de6a68d11 + unit test https://github.com/mapnik/mapnik/commit/a9d9f7ed996f69bf81c5fd469c920021e59b1609
Closing /cc @jakepruitt

**Closed by artemp** 2020-10-12 09:46 UTC
Labels: bug
