### ISSUE TITLE
OCCI not working with Oracle Instant Client 11.2

### ISSUE THREAD

**Issue by rolego** [mapnik/mapnik#2659] opened 2015-01-27 14:19 UTC
I compiled mapnik with Oracle Instant Client 11.2.0.4.0-1.x86_64.

At runtime I get the following error:
symbol lookup error: /usr/lib/oracle/11.2/client64/lib/libocci.so.11.1: undefined symbol: OCIEnvCreate

I tried various approaches such as link additional oracle libraries as proposed by the community, but without success.

Is this supposed to work? What am I doing wrong?

**Comment by springmeyer** [comment] 2015-01-27 19:45
`OCIEnvCreate` is not a symbol in Mapnik's occi plugin so this means that the problem is the oracle libraries themselves: you must be forgetting to link one or you have mixed up libraries from difference versions?

**Comment by tomhughes** [comment] 2015-01-27 19:47
Yes `OCIEnvCreate` is a standard Oracle client library interface - it should be in `libclntsh.so`.

**Comment by rolego** [comment] 2015-01-28 07:50
I finally managed to get this working:
in `<plugins/input/occi/build.py>` I had to change the required libraries from `<libraries = [ 'occi', 'ociei' ]>` to `<libraries = [ 'occi',  'clntsh' ]>` (replacing `<ociei>` by `<clntsh>`).

Apparently the libraries to be linked depend on the version of the Oracle Client libraries. :-/ Not sure if and how this should be integrated into the build. Maybe with a build flag?

**Comment by tomhughes** [comment] 2015-01-28 08:30
Well `libclntsh` is the only thing you normally need, or are the others something to do with the spatial stuff?

**Comment by tomhughes** [comment] 2015-01-28 08:46
The only documentation Oracle seem to provide on what to link against seems to be the makefiles for their demo applications, and as far as I can figure out `libclntsh` is the only thing they link against.

It seems that `libclntsh` is itself an amalgam of various other libraries created at installation time (for a full installation - the instant client comes with a prebuilt one) so while it may be possible to link against individual libraries instead that doesn't seem to be the recommended approach.

**Comment by artemp** [comment] 2015-01-28 12:09
@tomhughes @rolego @springmeyer  - makes total sense to link to client library. I'm closing here - re-open if any issues.

**Closed by artemp** 2015-01-28 12:09 UTC
