### ISSUE TITLE
shapeindex fails on 3d_point_empty.shp

### ISSUE THREAD

**Issue by tomhughes** [mapnik/mapnik#3184] opened 2015-11-22 19:46 UTC
Running shapeindex on `3d_point_empty.shp` from the test data repository gets stuck in an infinite loop. Output is:

```
max tree depth:8
split ratio:0.55
processing 3d_point_empty.shp
9994
length=50
version=1000
type=11
extent:box2d(0.0000000000000000,0.0000000000000000,0.0000000000000000,0.0000000000000000)
Content length mismatch for record number 16777216
Content length mismatch for record number 16777216
Content length mismatch for record number 16777216
```

The last line then repeats forever as the condition at the end of the loop that stops at the end of the file is never reached.

**Comment by artemp** [comment] 2015-11-23 10:04
@tomhughes - thanks for reporting! I couldn't reproduce on OS X but fixed potential infinite loop in c32166c. Could you verify latest master works for you ?

**Comment by tomhughes** [comment] 2015-11-23 10:21
That looks better, yes. Now I get:

```
max tree depth:8
split ratio:0.55
processing /tmp/mapnik-shp-tmp/3d_point_empty.shp
9994
length=50
version=1000
type=11
extent:box2d(0.0000000000000000,0.0000000000000000,0.0000000000000000,0.0000000000000000)
Content length mismatch for record number 16777216
No non-empty geometries in shapefile
done!
```

**Comment by artemp** [comment] 2015-11-23 10:34
@tomhughes 
`Content length mismatch for record number 16777216` <-- shouldn't be there .. ha I mistype `+` for `-` (user-error:) - proper fix is in ec074752cce6a1955d23068d20b345a04ecb1e11

**Comment by springmeyer** [comment] 2015-11-23 16:36
re-opening until we have a regression test.

**Comment by springmeyer** [comment] 2015-11-23 16:38
> re-opening until we have a regression test.

Looks like we lost this coverage when python tests moved out: https://github.com/mapnik/mapnik/commit/54dc9dd0f34a30e5a3b693af5ff02277c7f45147

**Comment by tomhughes** [comment] 2015-11-24 00:29
@springmeyer Well I found it when running the python tests ;-)

**Comment by artemp** [comment] 2015-11-24 10:52
ported to c++ ^ closing 
/cc @springmeyer @tomhughes

**Closed by artemp** 2015-11-24 10:52 UTC
Labels: bug, input.shape
