### ISSUE TITLE
Mapnik 3.0.0 Release

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2811] opened 2015-05-14 14:51 UTC
It has been a long while since we have had a release and I wanted to gain the attention of all @mapnik/devs. Later today I will be tagging a mapnik 3.0.0-rc2 tag, and I would really appreciate any efforts to:

* Provide more test coverage over current codebase
* Test current implementations

The goals now should be stability and code review. We are not planning on adding any new features until we get a 3.0 release!

**Comment by zerebubuth** [comment] 2015-05-14 15:55
:sparkles: :tada: :sparkles: :+1: 

But seriously, if there's anything I can do to help, I would be *ecstatically* happy to see 3.0.0.

**Comment by flippmoke** [comment] 2015-05-14 16:04
@zerebubuth Writing unit tests would be SO helpful:

https://coveralls.io/r/mapnik/mapnik

After moving out the python bindings our coverage dipped quite a bit and we have been working hard to replace many of the old python test, with real C++ unit tests. If you simply picked some key files from coveralls and decided to write unit tests for them here:

https://github.com/mapnik/mapnik/tree/master/test/unit

You would be a **HUGE** help.

**Comment by springmeyer** [comment] 2015-05-14 22:31
This afternoon @flippmoke and I reviewed all the tickets against 3.x and:

  - moved all non-critical tickets off the milestone
  - made sure we had assignments for each remaining ticket to either @springmeyer, @artemp, or @flippmoke 
  - confirmed that we think current master is ready at any time for a new rc2.

Plan is for @flippmoke to tag an rc2 tomorrow. We do not anticipate any major API changes from now on, so it is a great time to start ensuring all apps using mapnik are building well against rc2.

**Comment by der-stefan** [comment] 2015-05-15 10:40
Great news! I would like to help with the documentation in the Github Wiki. If someone has tasks for me, just contact me. Else I will just randomly look around in code and Wiki these days.

**Comment by flippmoke** [comment] 2015-05-15 19:01
@der-stefan updating the wiki would be amazing! In particular if since we moved the python bindings to https://github.com/mapnik/python-mapnik all the python binding Wiki stuff should be there!

**Comment by pnorman** [comment] 2015-05-19 06:13
I **absolutely** don't to delay 3.0 for it, but it would be worth doing a release of 2.3.0 as well, as that hasn't had any commits since Feb.

**Comment by flippmoke** [comment] 2015-05-19 13:36
@zerebubuth Thanks for your help porting some of the python unit tests!

**Comment by flippmoke** [comment] 2015-05-19 14:44
So the tag for rc2 is a bit delayed, that is my fault, I am sorry for not quite having everything done. We have closed out quite a few of the remaining tickets under milestone 3.x however!

**Comment by flippmoke** [comment] 2015-05-21 16:03
The `3.0.0-rc2` tag is out, and we are now in a feature freeze. Anything additionally added to `master` should be only to increase test coverage, clean up code, or fix potential bugs. Please coordinate with me if you are willing to help add more unit tests so that we don't double up writing any tests. 

I will again ask anyone to write any unit test possible as we want to make this release as stable as possible! 

Thank you @mapnik/devs for helping us get to this point!

**Comment by flippmoke** [comment] 2015-05-21 23:33
Wanted to point out that right now if you are new and wanting to test, the default `tar.gz` lacks the test data! Whoops! We are looking at correcting this in https://github.com/mapnik/mapnik/issues/2841. If you are new to get submodules and you checkout Mapnik via git, make sure to run:

```
git submodule init
git submodule update
```
 and the test data will be pulled down!

**Comment by gravitystorm** [comment] 2015-05-23 08:19
Is there an "incompatibility notes for cartographers" anywhere? I've been doing some testing of mapnik3 this week, and found a two things that I need to change in my 2.2.x stylesheets when upgrading to 3.x (text-dy on lines needs big adjustments and text-wrap-character leaves the wrap character visible). 

I can help with this since I'm porting a bunch of relatively complex styles.

**Comment by springmeyer** [comment] 2015-05-23 13:38
not yet @gravitystorm. starting to curate that would be great. thank you!

**Comment by springmeyer** [comment] 2015-05-23 16:21
o, @gravitystorm there is https://github.com/mapnik/mapnik/wiki/Api-changes-between-v2.2-and-v2.3 and https://github.com/mapnik/mapnik/wiki/Api-changes-between-v2.3-and-v3.0 which might help speed up the list of things to test. You could also add your findings there in a new section (or wherever you see fit let me know).

> I absolutely don't suggest delaying 3.0 for it, but it would be worth doing a release of 2.3.0 as well, as that hasn't had any commits since Feb.

I do not plan to release 2.3.0:

1) Yes, it would delay 3.0 and it would especially delay 3.0.1/3.0.2 because we'd be juggling stability bugfixes then in two unmergable branches. I don't have the bandwidth for this.
2) While 3.x has several major API changes in C++ and Python, the XML syntax should still be overwhelmingly back compatible. So cartographers upgrading to 3.x and helping flush out bugs and any unintended back compatibilities will be much more efficient.
3) 2.3.x is much less tested at this point and is pretty stale, so I consider it less stable for production than 3.x.

**Comment by camviluong** [comment] 2015-05-26 03:10
@springmeyer 
Is there an instruction to build Mapnik 3.0 with Visual Studio in Windows? I am waiting for it!

**Comment by BergWerkGIS** [comment] 2015-05-26 13:29
@camviluong 
The instructions for Windows can be found here:
https://github.com/mapbox/windows-builds

If you have the right environment set up (https://github.com/mapbox/windows-builds#requirements, only **VS2015 RC** supported at the moment) it basically boils down to

```
git clone https://github.com/mapbox/windows-builds.git
cd windows-builds
settings.bat "FASTBUILD=0"
scripts\build.bat
```

to automatically download and build all dependencies and mapnik itself.

**Beware:** depending on your machine it might take quite some RAM, CPU  and time.
Expect it to be somewhere between **one or two hours**.

Once we have pre-compiled dependencies this might come down to 20 to 50 minutes.

**Comment by flippmoke** [comment] 2015-05-26 18:54
@talaj I know you were trying to build on Windows ^

**Comment by flippmoke** [comment] 2015-05-27 00:02
@mapnik/devs I am about to push out a RC3, I know that not all issues in RC2 have been fixed, but we have addressed many issues that were preventing people from even compiling RC2. Additionally RC2 did not include test data in the download, which will be included in the RC3.

**Comment by camviluong** [comment] 2015-05-27 03:40
Thanks @BergWerkGIS . I am trying now

**Comment by camviluong** [comment] 2015-05-28 03:48
Hi @BergWerkGIS 

I have an error when call setting.bat "FASTBUILD=0"

![buildmapnikerror](https://cloud.githubusercontent.com/assets/6511508/7852393/026b0d04-0527-11e5-9b20-d70fe53ba13a.PNG)

**Comment by BergWerkGIS** [comment] 2015-05-28 11:13
@camviluong As this is `windows-builds` specific, let's continue over at https://github.com/mapbox/windows-builds/issues/41

**Comment by camviluong** [comment] 2015-05-29 09:27
hi @BergWerkGIS 

1. I succeed to build Mapnik Library, but there are 2 errors (failed in test case). Copy_move_test.cpp and image_painted_test.cpp. Can you tell me why? (images below)
![mapnik_failed_1_clip](https://cloud.githubusercontent.com/assets/6511508/7879962/5f2d6214-061f-11e5-8a9c-eff0ef8ae21b.png)
![mapnik_failed_2_clip](https://cloud.githubusercontent.com/assets/6511508/7879961/5f2cf478-061f-11e5-858c-83e9256136ce.png)

2. I have failed to build Node_Mapnik.
![mapnik_node_error_](https://cloud.githubusercontent.com/assets/6511508/7879992/92c758e6-061f-11e5-9711-8ad66c3149bb.PNG)

Thanks

**Comment by BergWerkGIS** [comment] 2015-05-29 16:25
@camviluong The mapnik library itself is fine, you can use it, the tests were faulty.
I just managed to get them working today.

If you update your local repository and build mapnik again. everything should be fine:

```
git pull
scripts\build mapnik
```

If you encounter other errors, please open an issue at
https://github.com/mapbox/windows-builds/issues/
as this is Windows specific, thanks.

**Comment by camviluong** [comment] 2015-05-30 02:27
I will open an issue next time,

Thanks @BergWerkGIS

**Comment by springmeyer** [comment] 2015-06-04 23:12
Overall update:

  - We are planning an RC4 tomorrow
  - Still aiming to release officially on Tuesday June 9th.

**Comment by flippmoke** [comment] 2015-06-05 23:03
Continued update here:

We are being held up by #2851 by are close to a solution. This is a complex update and will affect **a lot** of existing styles so we are a little concerned, but feel it should be done in Mapnik 3.0, not after.

The short story is that the `offset` parameter in the `LineSymoblizer` has been **positive to the right** of the direction of the line. The same is true the same with the `dy` parameter in the `TextSymbolizer`. 

**However**, this conflicts with the the orientation we are now enforcing internally in Mapnik. This causes polygon's paths to be changed from their source data at times, always causing exterior rings to be CCW and interior rings to be CW. (Unless your positive y axis is downward). 

This has caused confusion which direction a *positive* offset is for a polygon. We strongly feel that a positive offset should, extend outward from the polygon. This means that we need to change the `offset` paramater to be **positive to the left** of the line orientation. 


Here is a image of the the **CURRENT** setup. 
![image](https://cloud.githubusercontent.com/assets/1794907/8016657/21770794-0bac-11e5-9e94-150706369bf0.png)

Here is how the same style would look after the change:
![image](https://cloud.githubusercontent.com/assets/1794907/8016671/68e176fa-0bac-11e5-9ad9-ea181d6fbabc.png)

Another Example Before:

![image](https://cloud.githubusercontent.com/assets/1794907/8016682/8b5420fc-0bac-11e5-9802-a865b7753a21.png)

After:

![image](https://cloud.githubusercontent.com/assets/1794907/8016684/92ee5774-0bac-11e5-9e47-18f7d9edc0d9.png)

We hope to put out a RC4 with this change sometime on Monday, June 8th. Any feedback on these changes would be **greatly** appreciated. We were hopeful to get the release out June 9th, but this more then likely will be pushed back as we want adequate testing of RC4, especially with this impactful change to styles.

**Comment by pnorman** [comment] 2015-06-06 02:41
By current do you mean RC3 or Mapnik 2.2?

**Comment by springmeyer** [comment] 2015-06-06 03:32
@pnorman I think @flippmoke says `current` == RC3.

**Comment by flippmoke** [comment] 2015-06-08 03:52
By `current` I mean RC3 and 2.2.

**Comment by kapouer** [comment] 2015-06-09 06:34
Building on various arches: https://buildd.debian.org/status/package.php?p=mapnik

**Comment by pnorman** [comment] 2015-06-09 06:48
> By current I mean RC3 and 2.2.

You can't mean both, because they behave differently.

**Comment by pnorman** [comment] 2015-06-09 06:50
@kapouer Are you building with 1 job, or in parallel? Some of the errors are OOM errors, which can be fixed by single-threaded builds. Otherwise, it looks like there's still some memory consumption bugs with building :(

**Comment by kapouer** [comment] 2015-06-09 07:48
@pnorman all build flags are there https://tracker.debian.org/media/packages/m/mapnik/rules-3.0.0~rc3%2Bds-1

**Comment by pnorman** [comment] 2015-06-13 02:18
>> By current I mean RC3 and 2.2.
> You can't mean both, because they behave differently.

ping @flippmoke

**Comment by springmeyer** [comment] 2015-06-13 02:49
@kapouer can you get access to machines with more memory? How much do the ones have that are failing and what compiler/version are they using?

@pnorman @flippmoke means RC3 I think.

**Comment by kapouer** [comment] 2015-06-13 14:57
@springmeyer here are the machines:

Links to build logs can be found at 
https://buildd.debian.org/status/package.php?p=mapnik
by clicking on the "status" or "logs" column.

Builds are done with gcc 4.9.2 on debian/sid or testing.
Builds are done on one server, if it fails, it is retried on another server.
Tried mipsel servers:
https://db.debian.org/machines.cgi?host=mipsel-manda-01 with 8GB RAM
https://db.debian.org/machines.cgi?host=mipsel-aql-02 with 8GB RAM

Tried mips servers:
https://db.debian.org/machines.cgi?host=mips-aql-02 8GB RAM
https://db.debian.org/machines.cgi?host=lucatelli 1.8GB RAM (!)

On kfreebsd-i386, there is no information about how much RAM is available, i'm going to ask.
https://db.debian.org/machines.cgi?host=finzi
https://db.debian.org/machines.cgi?host=fils

Since it's not the first time i have had issues with building mapnik, i believe i made already some steps towards using less memory (building with -j1 and -g0). You also added flags like
NO_PREDEFINED_TERMINALS which i remember i backported to be able to build mapnik 2.2.

Interestingly, i used to remove `-ftemplate-depth-300`, and i removed it for mapnik 3.0 to see if it went good without removing it. I'm going to revert that removal.

**Comment by pnorman** [comment] 2015-06-14 03:26
> @pnorman @flippmoke means RC3 I think.

The image depicts current being something which depends on winding order, which is not the case for 3.0.0-rc3.

I'm building #2904 to see if it fixes the problems.

**Comment by pnorman** [comment] 2015-06-14 03:36
@springmeyer what's the current hash for node-mapnik needed for current master?

**Comment by pnorman** [comment] 2015-06-28 06:31
I'm prepared to call openstreetmap-carto ready. We need to add `vertical-alignment:middle` in a bunch of places, but that's not a blocker.

**Comment by flippmoke** [comment] 2015-06-29 14:49
@pnorman - @springmeyer has been spending a lot of time testing #2904 to make sure that it doesn't cause any issues and will be merging it sometime soon. This is likely to be what we release for 3.0.0.

**Comment by springmeyer** [comment] 2015-06-30 07:50
Update:

 - #2904 is merged
 - That leads to all code/bug related issues closed against 3.0.0
 - Except for #2928 and/or #2207 for which @artemp may land a fix tomorrow
 - Will issue an rc4 tomorrow mid-day PST for final testing after @artemp's last commits
 - After that the priority will be packaging, doc updates, supporting testing
 - Will tag v3.0.0 in a few days with the same basic code as rc4 assuming no more critical bugs arise that need fixing.

**Comment by springmeyer** [comment] 2015-06-30 19:32
> Except for #2928 and/or #2207 for which @artemp may land a fix tomorrow

Per chat with @artemp these fixes need some more time for testing. So I've created a 3.1.0 milestone and we'll track and fix against that future release: https://github.com/mapnik/mapnik/milestones/Mapnik%203.1.0

**Comment by flippmoke** [comment] 2015-06-30 19:43
I am now starting the process of releasing 3.0.0, I will check off the steps as they are completed.

## Final Testing
- [x] All tests passing in core on master
- [x] All tests passing in python mapnik from master branch builds
- [x] All tests passing in node mapnik from master branch builds

## Final Updates
- [ ] Update Changelog #2934 
- [ ] Update `version.hpp`
- [ ] Update CHANGELOG with latest hash of version

## Create Release
- [ ] Create Tag 
- [ ] Make source distribution for download from mapnik.org
- [ ] Update downloads page on mapnik.org
- [ ] Create official version on mason

## Announce
- [ ] Write Mapnik.org Blog Post
- [ ] Announce to group list
- [ ] Tweet new blog post
- [ ] Announce to packagers

**Comment by pnorman** [comment] 2015-06-30 20:24
Can we add the cartographer's notes into the list? Not sure where, but we should be able to point to them somewhere

**Comment by flippmoke** [comment] 2015-06-30 20:28
@pnorman thanks forgot to add that to list will in a second

**Comment by flippmoke** [comment] 2015-07-01 03:30
Update for everyone: we were about to release today but @pnorman found a potential show stopper in #2937 and we stopped at the last moment. We will be evaluating this further tomorrow and if possible doing the release tomorrow of 3.0.0

**Comment by flippmoke** [comment] 2015-07-06 14:35
We were so close, but we are still pushing forward the best we can. I spent lots of time on #2937 over the weekend and we are looking at possibly putting in some other bug fixes (that might be ready) such as #2929. The release is still likely delayed a bit again! SORRY! I will be speaking with @artemp and @springmeyer again today on the timeline for release and I will update once we talk about the plan more. If you have any input please let us know!

**Comment by springmeyer** [comment] 2015-07-07 03:04
- After a lot of work by everyone today we're back with no pending bugs against the 3.0.0 milestone.
 - Next action tomorrow is to return to testing current master and plugging through https://github.com/mapnik/mapnik/issues/2811#issuecomment-117316798.

**Comment by flippmoke** [comment] 2015-07-07 22:02
Boom: http://mapnik.org/news/release-3.0.0/

**Comment by springmeyer** [comment] 2015-07-08 01:36
Closing. Everything at [this list above](https://github.com/mapnik/mapnik/issues/2811#issuecomment-117316798) is done except the cartographers notes, which we can track at https://github.com/mapnik/mapnik/issues/2875. Thanks to @flippmoke for spearheading this release.

**Closed by springmeyer** 2015-07-08 01:36 UTC

**Comment by StevenLooman** [comment] 2015-07-08 19:53
Congratulations, good work!
