### ISSUE TITLE
Deterministic Line Label Placements

### ISSUE THREAD

**Issue by brandonreavis** [mapnik/mapnik#2929] opened 2015-06-29 06:20 UTC
After stripping away everything else, I am still having issues with label clipping / duplication when rendering text along a line across tile boundaries. This also happens with `clip` and `avoid-edges` set to false and this is without using vector tiles.

Here is a gist demonstrating the issue: https://gist.github.com/brandonreavis/08b61d286296af80f659.

In this case, shouldn't there only be one label placed instead of one per tile? Is there any way to force only one label to be placed in one spot across all of the tiles (ie. in the midpoint of the linestring) and not be influenced by the tile bounding box?

**Comment by talaj** [comment] 2015-06-30 14:20
I turned your gist into standard visual test case in https://github.com/mapnik/test-data-visual/pull/14.

If you look on result images they look fine for scale factor 1.0 because I used `buffer-size="128"`. This is how it looks without buffer:

![text-clip-1024-256-4x1-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/8432262/4df8d8f0-1f3f-11e5-9046-5882eedab72e.png)

With `buffer-size="128"` for comparison:

![text-clip-1024-256-4x1-1 0-agg-reference-2](https://cloud.githubusercontent.com/assets/1950911/8432314/a14043c2-1f3f-11e5-9458-cb380951f6a4.png)

So it looks like `buffer-size="128"` solves the issue but result for scale factor 2.0 still doesn't look as expected:

![text-clip-1024-256-4x1-2 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/8432400/1a95731e-1f40-11e5-8a76-1936c565d1e5.png)

Interestingly there is another approach than setting larger `buffer-size`. There is one [mystery condition](https://github.com/mapnik/mapnik/blob/bd9e580cd8a7ec0fe2d03b8034cf47bdc1bd799b/src/text/placement_finder.cpp#L372) in text rendering code which no one understand.
Great is that if I apply following diff which removes the dubious condition, the result images look as expected even without `buffer-size` for both scale factors.

```diff
--- a/src/text/placement_finder.cpp
+++ b/src/text/placement_finder.cpp
@@ -369,9 +369,7 @@ bool placement_finder::collision(const box2d<double> &box, const value_unicode_s
         margin = (text_props_->margin != 0 ? text_props_->margin : text_props_->minimum_distance) * scale_factor_;
         repeat_distance = text_props_->repeat_distance * scale_factor_;
     }
-    return !detector_.extent().intersects(box)
-        ||
-        (text_props_->avoid_edges && !extent_.contains(box))
+    return (text_props_->avoid_edges && !extent_.contains(box))
         ||
         (text_props_->minimum_padding > 0 &&
          !extent_.contains(box + (scale_factor_ * text_props_->minimum_padding)))
```

![text-clip-1024-256-4x1-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/8432833/aca33dd4-1f42-11e5-8ad0-f60f5ac8feec.png)
![text-clip-1024-256-4x1-2 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/8432834/aca94b2a-1f42-11e5-8d0f-9155011df323.png)

The patch above could be also major performance improvement. If I try to log steps of [tolerance_iterator](https://github.com/mapnik/mapnik/blob/master/include/mapnik/tolerance_iterator.hpp) with current mapnik, I'm getting very long list of placements tried:
```diff
--- a/include/mapnik/tolerance_iterator.hpp
+++ b/include/mapnik/tolerance_iterator.hpp
@@ -53,6 +53,7 @@ public:

     bool next()
     {
+        std::clog << "(" << value_ << ")";
         ++values_tried_;
         if (values_tried_ > 255)
         {
```

```
 $ test/visual/run text-clip -o -v                                                                                                                     [15:45:06]
(-0)(-0)(-1)(1)(-1.00069)(1.00069)(-2.00178)(2.00178)(-3.00348)(3.00348)(-4.00603)(4.00603)(-5.00979)(5.00979)(-6.01527)(6.01527)(-7.02317)(7.02317)(-8.03442)(8.0
3442)(-9.05034)(9.05034)(-10.0727)(10.0727)(-11.104)(11.104)(-12.1475)(12.1475)(-13.2077)(13.2077)(-14.2907)(14.2907)(-15.4049)(15.4049)(-16.5615)(16.5615)(-17.77
56)(17.7756)(-19.0676)(19.0676)(-20.465)(20.465)(-22.0047)(22.0047)(-23.7364)(23.7364)(-25.7267)(25.7267)(-28.0649)(28.0649)(-30.8707)(30.8707)(-34.304)(34.304)(-
38.579)(38.579)(-43.9817)(43.9817)(-50.8939)(50.8939)(-59.8249)(59.8249)(-71.4542)(71.4542)(-86.6869)(86.6869)(-106.728)(106.728)(-133.182)(133.182)(-168.184)(168
.184)(-214.569)(214.569)(-276.11)(276.11)(-357.814)(357.814)(-466.33)(466.33)(-0)(-0)(-1)(1)(-1.00069)(1.00069)(-2.00178)(2.00178)(-3.00348)(3.00348)(-4.00603)(4.
00603)(-5.00979)(5.00979)(-6.01527)(6.01527)(-7.02317)(7.02317)(-8.03442)(8.03442)(-9.05034)(9.05034)(-10.0727)(10.0727)(-11.104)(11.104)(-12.1475)(12.1475)(-13.2
077)(13.2077)(-14.2907)(14.2907)(-15.4049)(15.4049)(-16.5615)(16.5615)(-17.7756)(17.7756)(-19.0676)(19.0676)(-20.465)(20.465)(-22.0047)(22.0047)(-23.7364)(23.7364
)(-25.7267)(25.7267)(-28.0649)(28.0649)(-30.8707)(30.8707)(-34.304)(34.304)(-38.579)(38.579)(-43.9817)(43.9817)(-50.8939)(50.8939)(-59.8249)(59.8249)(-71.4542)(71
.4542)(-0)(-0)(-1)(1)(-1.00069)(1.00069)(-2.00178)(2.00178)(-3.00348)(3.00348)(-4.00603)(4.00603)(-5.00979)(5.00979)(-6.01527)(6.01527)(-7.02317)(7.02317)(-8.0344
2)(8.03442)(-9.05034)(9.05034)(-10.0727)(10.0727)(-11.104)(11.104)(-12.1475)(12.1475)(-13.2077)(13.2077)(-14.2907)(14.2907)(-15.4049)(15.4049)(-16.5615)(16.5615)(
-17.7756)(-0)(-0)(-1)(1)(-1.00069)(1.00069)(-2.00178)(2.00178)(-3.00348)(3.00348)(-4.00603)(4.00603)(-5.00979)(5.00979)(-6.01527)(6.01527)(-7.02317)(7.02317)(-8.0
3442)(8.03442)(-9.05034)(9.05034)(-10.0727)(10.0727)(-11.104)(11.104)(-12.1475)(12.1475)(-13.2077)(13.2077)(-14.2907)(14.2907)(-15.4049)(15.4049)(-16.5615)(16.561
5)(-17.7756)(17.7756)(-19.0676)(19.0676)(-20.465)(20.465)(-22.0047)(22.0047)(-23.7364)(23.7364)(-25.7267)(25.7267)(-28.0649)(28.0649)(-30.8707)(30.8707)(-34.304)(
34.304)(-38.579)(38.579)(-43.9817)(43.9817)(-50.8939)(50.8939)(-59.8249)(59.8249)(-71.4542)(71.4542)(-86.6869)(86.6869)(-106.728)(106.728)(-133.182)(133.182)(-168
.184)(168.184)(-214.569)(214.569)(-276.11)(276.11)(-357.814)"text-clip-1024-256-1.0" with agg... OVERWRITTEN (2036 different pixels)
(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(
-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)
(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-3
57.8)(357.8)(-466.3)(466.3)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)
(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1
)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4
.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(-0.0)
(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)
(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)
(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-357.8)"
text-clip-1024-256-1.0" with cairo... OVERWRITTEN (2057 different pixels)
(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(
-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)
(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-3
57.8)(357.8)(-466.3)(466.3)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)
(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1
)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4
.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(-0.0)
(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)
(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)
(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-357.8)"
text-clip-1024-256-1.0" with grid... OVERWRITTEN (1237 different pixels)
(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(
-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)
(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-3
57.8)(357.8)(-466.3)(466.3)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)
(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1
)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-
2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.
4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50
.9)(50.9)(-59.8)(59.8)(-71.5)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.
1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28
.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-21
4.6)(214.6)(-276.1)(276.1)(-357.8)"text-clip-1024-256-2.0" with agg... OVERWRITTEN (5627 different pixels)
(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(
-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)
(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-3
57.8)(357.8)(-466.3)(466.3)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)
(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1
)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-
2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.
4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50
.9)(50.9)(-59.8)(59.8)(-71.5)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.
1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28
.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-21
4.6)(214.6)(-276.1)(276.1)(-357.8)"text-clip-1024-256-2.0" with cairo... OVERWRITTEN (5686 different pixels)
(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(
-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)
(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-214.6)(214.6)(-276.1)(276.1)(-3
57.8)(357.8)(-466.3)(466.3)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)
(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1
)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-
2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.
4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50
.9)(50.9)(-59.8)(59.8)(-71.5)(-0.0)(-0.0)(-1.0)(1.0)(-1.0)(1.0)(-2.0)(2.0)(-3.0)(3.0)(-4.0)(4.0)(-5.0)(5.0)(-6.0)(6.0)(-7.0)(7.0)(-8.0)(8.0)(-9.1)(9.1)(-10.1)(10.
1)(-11.1)(11.1)(-12.1)(12.1)(-13.2)(13.2)(-14.3)(14.3)(-15.4)(15.4)(-16.6)(16.6)(-17.8)(17.8)(-19.1)(19.1)(-20.5)(20.5)(-22.0)(22.0)(-23.7)(23.7)(-25.7)(25.7)(-28
.1)(28.1)(-30.9)(30.9)(-34.3)(34.3)(-38.6)(38.6)(-44.0)(44.0)(-50.9)(50.9)(-59.8)(59.8)(-71.5)(71.5)(-86.7)(86.7)(-106.7)(106.7)(-133.2)(133.2)(-168.2)(168.2)(-21
4.6)(214.6)(-276.1)(276.1)(-357.8)"text-clip-1024-256-2.0" with grid... OVERWRITTEN (3843 different pixels)

Visual rendering: 0 failed / 0 passed / 6 overwritten / 0 errors
```

Patched version for comparison:
```
 $ test/visual/run text-clip -o -v
(-0)(-0)(-0)(-0)"text-clip-1024-256-1.0" with agg... OVERWRITTEN (2036 different pixels)
(-0.0)(-0.0)(-0.0)(-0.0)"text-clip-1024-256-1.0" with cairo... OVERWRITTEN (2057 different pixels)
(-0.0)(-0.0)(-0.0)(-0.0)"text-clip-1024-256-1.0" with grid... OVERWRITTEN (1237 different pixels)
(-0.0)(-0.0)(-0.0)(-0.0)"text-clip-1024-256-2.0" with agg... OVERWRITTEN (5627 different pixels)
(-0.0)(-0.0)(-0.0)(-0.0)"text-clip-1024-256-2.0" with cairo... OVERWRITTEN (5686 different pixels)
(-0.0)(-0.0)(-0.0)(-0.0)"text-clip-1024-256-2.0" with grid... OVERWRITTEN (3843 different pixels)

Visual rendering: 0 failed / 0 passed / 6 overwritten / 0 errors
```

**Comment by brandonreavis** [comment] 2015-06-30 16:00
Beautiful work! Removing `!detector_.extent().intersects(box)` made it work just as I was hoping for.  Any idea why it is in there? I agree that it seems redundant with 'avoid-edges'. It also seems unnecessary with the `clip` option on the TextSymbolizer which prevents any label from being placed outside of the detector extent.

Chopping it out could break some styles that inadvertently used it to repeat labels (one in each tile), but maybe this is reasonable for the 3.x release given that people should be using `clip="true"` for cases like this.

The `buffer-size` fix just lessens the probability of happening, but, as you noticed, it still happens. In my original use-case where I noticed this I was using a `buffer-size` of 256.

**Comment by talaj** [comment] 2015-06-30 18:56
Problem with `!detector_.extent().intersects(box)` condition is that `box` means bounding box of single glyph. The collision detector stores per glyph bounding boxes (except of angled text https://github.com/mapnik/mapnik/issues/2207). So it leads to discarded placement when single glyph is out of extent of collision detector. Placement with one glyph outside of tile should be perfectly valid in my opinion.
I think it's some very old relict from times when text bboxes wasn't stored per glyph, but I have to dive into git history to be certain.

**Comment by springmeyer** [comment] 2015-06-30 19:28
Fantastic work uncovering this @brandonreavis and @talaj - I'm in agreement that this fix looks promising / likely a very old/lurking bug. But I think it warrants good testing along with the other text fixes on our radar: #2928 and #2207. So, I'm assigning to v3.1.0 which I anticipate will be the next release after 3.0.0.

**Comment by brandonreavis** [comment] 2015-06-30 19:59
Awesome @talaj and @springmeyer. Sounds good to me.

**Comment by talaj** [comment] 2015-07-01 11:38
That condition is almost as old as Mapnik itself. It appeard in https://github.com/mapnik/mapnik/commit/8d51cb421bf0ca98ee9bb721e2276ab5207904a8 ([this line](https://github.com/mapnik/mapnik/blob/8d51cb421bf0ca98ee9bb721e2276ab5207904a8/src/placement_finder.cpp#L362)) from Nov 2, 2007 :-).

**Comment by springmeyer** [comment] 2015-07-01 21:40
> That condition is almost as old as Mapnik itself. It appeared in 8d51cb4 (this line) from Nov 2, 2007 :-).

Wow, good detective work :) Given this has been in place forever we should be very cautious in removing until we understand exactly how this will change behavior.

It seems like the core tradeoff here the relative cost of `trying lots of placements` vs potentially `rendering text off the canvas`. Given a geometry that extends way outside the bounds of a tile we don't want to pay the penalty of asking Freetype to render pixels that will never be seen. But in #2937 we see cases where trying placements can be much more expensive than just rendering off canvas and moving on (or at least that is what I'm guessing is happening when this patch speeds up #2937).

**Comment by brandonreavis** [comment] 2015-07-02 04:35
I still am working to familiarize myself with the inner workings of Mapnik, but to me it seems like you could get the best of both worlds by quickly picking a placement independent of the map extent, then test whether or not it should be drawn in the `render` methods. Checking if a glyph overlaps the map extent and just skipping drawing seems way cheaper than checking if a glyph overlaps the map, picking a new placement, checking if it overlaps the map, picking a new placement etc.

I can try to throw together some more exhaustive test cases that would highlight the differences soon.

**Comment by springmeyer** [comment] 2015-07-02 04:49
Sounds good @brandonreavis - more test cases will be awesome. I'm hoping @talaj will have more ideas too

> Placement with one glyph outside of tile should be perfectly valid in my opinion.

I agree: unless `avoid-edges:true` it seems reasonable for text to be placed/rendered that might have some or nearly all glyphs outside the tile extent.

**Comment by talaj** [comment] 2015-07-02 07:29
I agree with @brandonreavis, text placed independent of the tile borders will lead to
* deterministic placements (which solves this issue and will improve overall map determinism)
* it will be faster in terms of number of placements tried due to collision with tile extent
* it could allow set smaller `buffer-size` (thanks to more deterministic placements, long text over several tiles is now problematic; improves performance)
* glyphs out of the tile extent should not hit text renderer (no performance penalty)

I also agree with @springmeyer it should be extensively tested for possible drawbacks. I was checking visual tests and rendering some maps and found nothing wrong so far. I will also try some performance tests.

**Comment by artemp** [comment] 2015-07-03 09:00
@talaj - `!detector_.extent().intersects(box)` <-- looks redundant and good to remove. I can't see how this test becomes expensive unless we pass wrong extent to quad-tree somewhere

**Comment by talaj** [comment] 2015-07-03 10:07
@artemp I think it's expensive because it produces a lot of collisions on tile's borders by iterating over possible placements by [tolerance_iterator](https://github.com/mapnik/mapnik/blob/master/include/mapnik/tolerance_iterator.hpp). See the long print out above.

Some numbers for the test above. Testing with 100 iterations.

Current master:
```
 $ test/visual/run text-clip -v -d -i 100
"text-clip-1024-256-4x1-1.0" with agg... OK (2517 milliseconds)
"text-clip-1024-256-4x1-1.0" with cairo... OK (3844 milliseconds)
"text-clip-1024-256-4x1-1.0" with grid... OK (2146 milliseconds)
"text-clip-1024-256-4x1-2.0" with agg... OK (2137 milliseconds)
"text-clip-1024-256-4x1-2.0" with cairo... OK (3453 milliseconds)
"text-clip-1024-256-4x1-2.0" with grid... OK (2066 milliseconds)
```

Without `!detector_.extent().intersects(box)`:
```
 $ test/visual/run text-clip -v -d -i 100
"text-clip-1024-256-4x1-1.0" with agg... OK (1426 milliseconds)
"text-clip-1024-256-4x1-1.0" with cairo... OK (2564 milliseconds)
"text-clip-1024-256-4x1-1.0" with grid... OK (1562 milliseconds)
"text-clip-1024-256-4x1-2.0" with agg... OK (1491 milliseconds)
"text-clip-1024-256-4x1-2.0" with cairo... OK (2625 milliseconds)
"text-clip-1024-256-4x1-2.0" with grid... OK (1667 milliseconds)
```

Current master with `label-position-tolerance="1"`. No text is rendered, of course.
```
 $ test/visual/run text-clip -v -d -i 100
"text-clip-1024-256-4x1-1.0" with agg... OK (1391 milliseconds)
"text-clip-1024-256-4x1-1.0" with cairo... OK (2812 milliseconds)
"text-clip-1024-256-4x1-1.0" with grid... OK (1526 milliseconds)
"text-clip-1024-256-4x1-2.0" with agg... OK (1412 milliseconds)
"text-clip-1024-256-4x1-2.0" with cairo... OK (2827 milliseconds)
"text-clip-1024-256-4x1-2.0" with grid... OK (1628 milliseconds)
```

**Comment by artemp** [comment] 2015-07-03 11:29
@talaj - thanks for the info!

**Comment by flippmoke** [comment] 2015-07-06 14:29
It concerns me with tiles if we have images like this:

![image](https://cloud.githubusercontent.com/assets/1794907/8524540/7c488436-23c1-11e5-98ab-6674c3dbbc9a.png)

The other half of the road name would not be rendered in the same spot by the tile below would it?

**Comment by talaj** [comment] 2015-07-06 20:55
@flippmoke I will create test for it tomorrow. I think it definitely will be on the same spot if buffer size is used. Otherwise there is chance it won't render on the below tile - the line might not be part of the below tile extent.

**Comment by springmeyer** [comment] 2015-07-06 23:20
> I think it definitely will be on the same spot if buffer size is used.

Correct. And this is the intended behavior if `allow-edges:false` (the default). In all my local testing so far:

  - I'm seeing no problems and very few visible changes
  - the visual test changes all look good - they are now working as intended.

Going to do a bit more testing and then will plan to merge.

**Comment by springmeyer** [comment] 2015-07-07 00:43
Further testing has indicated that after this patch we will allow rendering text off canvas which is wasteful. So I'll be following up with a commit after this is merged that:

   - avoids rendering text that is fully off canvas (which will now happen after this patch)
   - will not update visual tests because it should make no difference except help with performance

**Closed** 2015-07-07 01:04 UTC

**Comment by springmeyer** [comment] 2015-07-07 01:37
We're done here. To recap:

  - Avoiding "cut-off" text across tiles is hard and imperfect. One strategy is to avoid text near edges (`text-avoid-edges:true`). The other is to be okay with text near or across edges and work to ensure that text is placed in the same place across tiles. This can be very difficult (and require consistent sorting or avoidance of other collisions). But a major prerequisite to this being able to work is simply asking Mapnik to allow text near edges with `text-avoid-edges:false`. Despite this being the default it was not actually working. The merge in #2949 fixes this behavior. 
  - Thanks @brandonreavis for finding this ancient bug
  - Thanks @talaj for the fix and the new tiled visual tests (https://github.com/mapnik/mapnik/pull/2930)

> avoids rendering text that is fully off canvas (which will now happen after this patch)

done in 3f91186
