### ISSUE TITLE
Make scale-hsla image filter work outside [0,1] range

### ISSUE THREAD

**Issue by tkafka** [mapnik/mapnik#3052] opened 2015-09-01 14:07 UTC
Hi, I was rendering a hillshade (represented by a grayscale bitmap where white = light areas, black = shaded ones). As I wanted to composite lights and shadows separately, I created two different layers (and styles):

- light should be shifted and scale so that what is below #888 is black - so that the result could be applied with `screen` comp op to lighten the sunny sides
- shadow should be shifted inversely, so that what is above #888 is white, so that result could be applied with `multiply` to darken the dark side

I expected this to accomplish it:

	<Style name="hillshade-light" image-filters="scale-hsla(0,1, 0,1, -1,1, 1,0)" comp-op="screen">
	    <Rule>
	      <RasterSymbolizer scaling="bilinear" opacity="1"/>
	    </Rule>
	</Style>

	<Style name="hillshade-shadow" image-filters="scale-hsla(0,1, 0,1, 0,2, 1,0)" comp-op="overlay">
	    <Rule>
	      <RasterSymbolizer scaling="bilinear" opacity="1"/>
	    </Rule>
	</Style>

However, mapnik throws an error: `scale-hsla values must be between 0 and 1`.

I don't see the reason for this, allowing values outside the range and clipping the result should work well without breaking anything.

Could this be implemented please? Thank you!

**Comment by talaj** [comment] 2015-09-02 15:49
I agree. [The formula](https://github.com/mapnik/mapnik/blob/0b6b11b9cf03c1431aeab01c82e6bdf676b99e35/include/mapnik/image_filter.hpp#L658-L660) for `scale-hsla` is following (saturation, lightness and alpha looks the same):

```
hue2 = h0 + hue * (h1 - h0)
```

With `h0 = 0` and `h1 = 1` from your example:

```
hue2 = 0 + hue * (1 - 0) = hue
```

This is identity, and makes sense not to transform a particular component.

Inversion with `h0 = 1` and `h1 = 0`:

```
hue2 = 1 + hue * (0 - 1) = 1 - hue
```

`h0 = 0` and `h1 = 2` maps [0, 0.5] to [0, 1], [0.5, 1] is clipped:

```
hue2 = 0 + hue * (2 - 0) = 2 * hue
```

`h0 = -1` and `h1 = 1` clips values in [0, 0.5], [0.5, 1] is mapped to [0, 1]:

```
hue2 = -1 + hue * (1 + 1) = -1 + 2 * hue
```

So it makes perfect sense not to limit `scale-hsla` parameters by (0, 1).

**Comment by flippmoke** [comment] 2015-09-03 14:09
@talaj @tkafka my initial concern here is that this was put into place for some reason, perhaps the algorithm falls off at some point? It may not work if a color is already at 255 etc.

**Comment by talaj** [comment] 2015-09-03 20:25
The algorithm is very simple and straightforward. It just linearly scales color components in HSL space and then it clips the result to [0, 1]. There is no space to fail.

The problem is that some useful scales are not achievable due to the limit.

**Comment by artemp** [comment] 2015-09-08 10:24
@talaj @tkafka @flippmoke - looks good, merged

**Closed** 2015-09-22 14:57 UTC
