### ISSUE TITLE
osm-carto shield drop in Mapnik 3.0.16 and 17

### ISSUE THREAD

**Issue by kocio-pl** [mapnik/mapnik#3812] opened 2017-12-02 03:01 UTC
Current code from [OpenStreetMap Carto](https://github.com/gravitystorm/openstreetmap-carto) rendered under Kosmtik with Mapnik 3.0.17 (also in 3.0.16) drops the road shields like this:

3.0.15 (from npm)
![hkmhliln](https://user-images.githubusercontent.com/5439713/33511080-1f958e3c-d715-11e7-89ee-6549d0c65623.png)

3.0.17 (compiled)
![n49dxzf2](https://user-images.githubusercontent.com/5439713/33511082-238c5d22-d715-11e7-91ea-c89d1d6b42e7.png)

**Comment by talaj** [comment] 2017-12-02 08:48
Bisected to https://github.com/mapnik/mapnik/commit/d09f49b3770193ae8149b2eab5a950d8bef2e822.

**Comment by talaj** [comment] 2017-12-02 09:04
Reproducible with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shields/motorway_1x1_z18.svg

**Comment by kocio-pl** [comment] 2017-12-02 13:29
The same problem with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/plaque.svg

**Comment by talaj** [comment] 2017-12-04 12:36
@artemp, do you have any idea?

**Comment by artemp** [comment] 2017-12-04 13:04
@talaj - I'm going to look into this. I tried `svg2png` and output is OK. Maybe be this regression is due to how SVG dimensions are calculated ? <- Just a wild assumption  at the moment.

**Comment by artemp** [comment] 2017-12-04 13:05
@talaj - if you have functional setup to try - could you modify SVG and replace 100% width/height with actual pixel numbers and see if shields are re-appear ?

**Comment by talaj** [comment] 2017-12-04 13:08
I was trying `svg2png` on 3.0.x branch and output was an empty image. I will try it again with your proposal to set a fixed size.

**Comment by talaj** [comment] 2017-12-04 13:12
I was trying it on v3.0.17 tag to be more precise.

**Comment by talaj** [comment] 2017-12-04 13:28
@artemp, yes, changing % to px helped.

**Comment by artemp** [comment] 2017-12-04 13:46
@talaj - great, thanks. Let me think what would be the best way ti fix this.. also are you sure `svg2png` is a correct version ?

**Comment by talaj** [comment] 2017-12-04 13:53
> also are you sure svg2png is a correct version ?

I hope it is, I've cleaned and built it all. I've also tried it as a visual test and it was the same.

**Comment by artemp** [comment] 2017-12-06 10:13
I pushed the fix in https://github.com/mapnik/mapnik/commit/5227f84e077f8144d070157c778fd1e9dc939115.  The issue was applying aspect ration logic when width and height are use percentage values. Percentage values for width and height only make sense in context of existing enclosing container element.  @kocio-pl @talaj - any feedback on this fix ? Anything else we can do here ? cheers.

**Comment by kocio-pl** [comment] 2017-12-06 15:41
How could I compile node-mapnik with Mapnik version installed at `/opt/mapnik` for example? I see no such information how to compile it with the specific Mapnik location, just an "existing version of Mapnik on your system": 

https://github.com/mapnik/node-mapnik#source-build

**Comment by talaj** [comment] 2017-12-06 15:58
@kocio-pl - I think that all locations node-mapnik needs to know are derived from `mapnik-config`. You have to add a location to `mapnik-config` to the `PATH` variable. I think that it should look like this in your case:

```sh
export PATH=/opt/mapnik/bin:$PATH
```

**Comment by kocio-pl** [comment] 2017-12-06 16:02
I have also Mapnik installed from system package (with library in `/usr/lib`), do you think it will choose the proper library location (`/opt/mapnik/lib`)?

**Comment by talaj** [comment] 2017-12-06 16:10
Yes, in build time, it will. `/opt/mapnik/bin:$PATH` puts `/opt` location prior to anything else. For runtime, you have to say to the system, that it should prefer libs from `/opt/mapnik/lib`:

```sh
export LD_LIBRARY_PATH=/opt/mapnik/lib
```

To be sure, I would perform both exports before build and run.

**Comment by kocio-pl** [comment] 2017-12-06 16:37
This fix seems to do the job, both shields and plaques are visible now, thanks!

Fortunately I don't have to worry about runtime, because Kosmtik uses the one that node-mapnik is compiled with (which is easy to check - I just moved the packaged library away and it's still rendering). 

I have `could not create BreakIterator: U_MISSING_RESOURCE_ERROR` errors, so it looks like Debian 3.0.17 package does something with ICU to avoid it, because when using the packaged version there are no problems with breaking lines.

**Comment by talaj** [comment] 2017-12-06 16:55
Maybe you have to set path to ICU data before you run Kosmtik:

```sh
export ICU_DATA=$(icu-config --icudatadir)
```

**Comment by kocio-pl** [comment] 2017-12-06 19:09
Earlier I was playing with `boostrap.sh`, which installed Mason packages probably and `make clean` nor setting `ICU_DATA` path ware effective to use system libraries - it still was trying to use Mason version. Maybe it's something about .dat file (icudt57l.dat) - Mason package seems to have it, but Ubuntu packages don't, even if both are using ICU version 57.1.

So I've made a clean cloning and compiled it like this (for the record, because it's easy to get lost with details):
```
git clone https://github.com/mapnik/mapnik.git
cd mapnik
git checkout v3.0.x
git submodule update --init
./configure PREFIX=/opt/mapnik
JOBS=4 make
make install
```

Then I made a clean node-mapnik clone and compiled it like this:
```
git clone https://github.com/mapnik/node-mapnik
cd node-mapnik
export PATH=/opt/mapnik/bin:$PATH
make release_base
```

But when trying to open Kosmtik with hand crafted symlink to that version, I get:
```
Error: /media/hdd/home/kocio/devel/node-mapnik/lib/binding/mapnik.node: undefined symbol: _ZN6mapnik14save_to_stringINS_9image_anyEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKS7_
```

**Comment by talaj** [comment] 2017-12-06 21:00
> Earlier I was playing with `boostrap.sh`, which installed Mason packages probably and make clean nor setting `ICU_DATA` path ware effective to use system libraries - it still was trying to use Mason version. 

It was probably because `make clean` leaves file `config.py` which contains a Mason build configuration. There is `make distclean` for removing this file, take a look into the Makefile.

I'm using `git clean -xfd` for proper clean, but one should be aware that it will wipe out everything not indexed by git.

> undefined symbol: _ZN6mapnik14save_to_stringINS_9image_anyEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKS7_

This seems a bit like Mapnik was built with bootstrap and node-mapnik not. This combination is not compatible. The `__cxx11` thing denotes C++11 ABI, which [is not used by bootstrap](https://github.com/mapnik/mapnik/blob/54532cecb56d9d8ecd7e3b54659ede285b7973f2/bootstrap.sh#L88), but otherwise it is default with recent compilers.

**Comment by talaj** [comment] 2017-12-07 15:42
@artemp - I can confirm the bug is fixed in 3.0.x, but the problem exists also in master.

The SVG test runner would come in handy now.

**Comment by artemp** [comment] 2017-12-07 17:24
@talaj - thanks, I'll cherry-pick into master.

**Closed** 2017-12-09 02:14 UTC
Labels: bug, svg

**Comment by kocio-pl** [comment] 2017-12-09 04:18
> This seems a bit like Mapnik was built with bootstrap and node-mapnik not. This combination is not compatible. The __cxx11 thing denotes C++11 ABI, which is not used by bootstrap, but otherwise it is default with recent compilers.

1. When I ran `boostrap.sh` before configure, I was able to compile both mapnik and node-mapnik, but trying to render under Kosmtik failed.

2. When I skipped  `boostrap.sh` and just modified configure to use this flag:

`./configure PREFIX=/opt/mapnik CUSTOM_CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0`

Mapnik compilation failed:

```
utils/mapnik-index/mapnik-index.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueISt6vectorISsSaISsEEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorISsSaISsEEcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
```

Probably 1. has something to do with lack of Mason dependencies in my system and 2. means that my system boost libs were compiled with some C++11 features:

`Checking whether Boost was compiled with C++11 scoped enums ... yes`

**Comment by talaj** [comment] 2017-12-09 08:11
This is my bad, I should have warned you that the bootstrap was created only for development of Mapnik. I think that install instructions are also not clear in this respect. The only reason for bootstrap to exist is to run Mapnik and its tests under the same versions of dependencies, because tests are fragile to dependencies.

To deploy Mapnik against Kosmtik means you need (at least should) to build without bootstrap.

**Comment by kocio-pl** [comment] 2017-12-09 15:29
>This is my bad, I should have warned you that the bootstrap was created only for development of Mapnik. I think that install instructions are also not clear in this respect. 

OK, I realized it in the meantime and I'm ready to test. It would be good to make documentation more clear in this respect at the end of the day. But now I still think how exactly to compile Mapnik from repo so that I could test in in Kosmtik.

> To deploy Mapnik against Kosmtik means you need (at least should) to build without bootstrap.

This is what I did - with and without C++11 ABI flag. Both failed: 
- plain compiling (https://github.com/mapnik/mapnik/issues/3812#issuecomment-349742601) gave me a problem with running Kosmtik (node-mapnik using C++11 ABI)
- adding flag I have problem with compiling Mapnik (system Boost using C++11 ABI)

Using boostrap.sh is almost good, since everything is compiled with proper dependencies (prepared for Meson packaging), but at the end something is missing (Kosmtik worked, but showed nothing - it complained about problem with rendering images, so probably some resources missing).

**Comment by talaj** [comment] 2017-12-10 10:39
> plain compiling (#3812 (comment)) gave me a problem with running Kosmtik (node-mapnik using C++11 ABI)

I think that problem was not properly cleaned Mapnik after bootstrap build. Mapnik was then compiled with bootstrap configuration again.

> adding flag I have problem with compiling Mapnik (system Boost using C++11 ABI)

That flag will not fix anything. It is used by the bootstrap because all Mason packages are built with this flag, but you cannot not use it when building against system libraries with C++11 ABI .

You can check, out of curiosity, that your system libraries use C++11 ABI. Here on Debian stretch:

```console
$ nm -D -C /usr/lib/x86_64-linux-gnu/libboost_program_options.so | grep value_semantic_codecvt_helper
0000000000059f30 T boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const
```

Notice the `__cxx11`.

I would try to build it again without bootstrap with properly cleaned up everything.

**Comment by talaj** [comment] 2017-12-10 10:42
> I think that problem was not properly cleaned Mapnik after bootstrap build. Mapnik was then compiled with bootstrap configuration again.

I'm sorry, I now see taht you are doing compilation from clean clone. Let mi think again...

**Comment by kocio-pl** [comment] 2017-12-11 02:14
I have learned that there are some instructions for Mapnik on Ubuntu, I will try to follow them:

https://github.com/mapnik/mapnik/wiki/UbuntuInstallation
