### ISSUE TITLE
error: no matching function for call to ‘assertion_failed

### ISSUE THREAD

**Issue by strk** [mapnik/mapnik#3381] opened 2016-03-23 16:12 UTC
As of 0fb587875e3c2802736f3d0367de39b7b3a6a91d, with libboost 1.54 and all submodules up-to-date:

```
In file included from /usr/include/boost/geometry/core/tag.hpp:18:0,
                 from /usr/include/boost/geometry/geometries/register/linestring.hpp:19,
                 from include/mapnik/geometry_adapters.hpp:32,
                 from test/unit/serialization/wkb_test.cpp:5:
/usr/include/boost/geometry/algorithms/not_implemented.hpp: In instantiation of ‘struct boost::geometry::nyi::not_implemented_error<boost::geometry
::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING, void>’:
/usr/include/boost/geometry/algorithms/not_implemented.hpp:103:8:   required from ‘struct boost::geometry::not_implemented<boost::geometry::multi_l
inestring_tag, boost::geometry::multi_linestring_tag, void>’
/usr/include/boost/geometry/algorithms/equals.hpp:165:8:   required from ‘struct boost::geometry::dispatch::equals<mapnik::geometry::multi_line_str
ing<double>, mapnik::geometry::multi_line_string<double>, boost::geometry::multi_linestring_tag, boost::geometry::multi_linestring_tag, 2ul, false>
’
/usr/include/boost/geometry/algorithms/equals.hpp:256:72:   required from ‘static bool boost::geometry::dispatch::devarianted_equals<Geometry1, Geo
metry2>::apply(const Geometry1&, const Geometry2&) [with Geometry1 = mapnik::geometry::multi_line_string<double>; Geometry2 = mapnik::geometry::mul
ti_line_string<double>]’
/usr/include/boost/geometry/algorithms/equals.hpp:374:44:   required from ‘bool boost::geometry::equals(const Geometry1&, const Geometry2&) [with G
eometry1 = mapnik::geometry::multi_line_string<double>; Geometry2 = mapnik::geometry::multi_line_string<double>]’
test/unit/serialization/wkb_test.cpp:64:48:   required from ‘{anonymous}::spatially_equal_visitor::result_type {anonymous}::spatially_equal_visitor
::operator()(const T&, const T&) const [with T = mapnik::geometry::multi_line_string<double>; {anonymous}::spatially_equal_visitor::result_type = b
ool]’
deps/mapbox/variant/variant.hpp:459:92:   recursively required from ‘static R mapbox::util::detail::binary_dispatcher<F, V, R, T, Types ...>::apply
_const(const V&, const V&, F&&) [with F = const {anonymous}::spatially_equal_visitor&; V = mapnik::geometry::geometry<double>; R = bool; T = mapnik
::geometry::point<double>; Types = {mapnik::geometry::line_string<double>, mapnik::geometry::polygon<double, mapnik::geometry::rings_container>, ma
pnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>, mapbox::util::recursive_
wrapper<mapnik::geometry::geometry_collection<double> >}]’
deps/mapbox/variant/variant.hpp:459:92:   required from ‘static R mapbox::util::detail::binary_dispatcher<F, V, R, T, Types ...>::apply_const(const
 V&, const V&, F&&) [with F = const {anonymous}::spatially_equal_visitor&; V = mapnik::geometry::geometry<double>; R = bool; T = mapnik::geometry::
geometry_empty; Types = {mapnik::geometry::point<double>, mapnik::geometry::line_string<double>, mapnik::geometry::polygon<double, mapnik::geometry
::rings_container>, mapnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>, ma
pbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> >}]’
deps/mapbox/variant/variant.hpp:798:100:   required from ‘static decltype (mapbox::util::detail::binary_dispatcher<F, V, R, Types ...>::apply_const
(v0, v1, forward<F>(f))) mapbox::util::variant<Types>::binary_visit(const V&, const V&, F&&) [with F = const {anonymous}::spatially_equal_visitor&;
 V = mapnik::geometry::geometry<double>; R = bool; Types = {mapnik::geometry::geometry_empty, mapnik::geometry::point<double>, mapnik::geometry::li
ne_string<double>, mapnik::geometry::polygon<double, mapnik::geometry::rings_container>, mapnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>, mapbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> >}; decltype (mapbox::util::detail::binary_dispatcher<F, V, R, Types ...>::apply_const(v0, v1, forward<F>(f))) = bool]’
include/mapnik/util/variant.hpp:70:54:   required from ‘decltype (V:: binary_visit(v0, v1, f)) mapnik::util::apply_visitor(F&&, const V&, const V&) [with F = const {anonymous}::spatially_equal_visitor&; V = mapnik::geometry::geometry<double>; decltype (V:: binary_visit(v0, v1, f)) = bool]’
test/unit/serialization/wkb_test.cpp:37:75:   required from here
/usr/include/boost/geometry/algorithms/not_implemented.hpp:64:5: error: no matching function for call to ‘assertion_failed(mpl_::failed************ (boost::geometry::nyi::not_implemented_error<boost::geometry::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING, void>::THIS_OPERATION_IS_NOT_OR_NOT_YET_IMPLEMENTED::************)(mpl_::assert_::types<boost::geometry::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING, void, mpl_::na>))’
     BOOST_MPL_ASSERT_MSG
     ^
```

**Comment by MaksVasilev** [comment] 2016-04-19 07:03
boost 1.54

```
clang++ -o utils/shapeindex/shapeindex utils/shapeindex/shapeindex.o -Ldeps/agg -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/lib -L/lib64 -L/usr/lib64 -L/usr/lib/postgresql94/lib64 -lmapnik -lboost_program_options -lboost_system -licuuc
In file included from test/unit/serialization/wkb_test.cpp:5:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/include/boost/geometry.hpp:17:
In file included from /usr/include/boost/geometry/geometry.hpp:35:
In file included from /usr/include/boost/geometry/strategies/strategies.hpp:25:
In file included from /usr/include/boost/geometry/strategies/intersection.hpp:23:
In file included from /usr/include/boost/geometry/strategies/cartesian/cart_intersect.hpp:20:
In file included from /usr/include/boost/geometry/algorithms/detail/assign_values.hpp:29:
In file included from /usr/include/boost/geometry/algorithms/append.hpp:24:
In file included from /usr/include/boost/geometry/geometries/concepts/check.hpp:33:
/usr/include/boost/geometry/algorithms/not_implemented.hpp:64:5: error: no matching function for call to 'assertion_failed'
    BOOST_MPL_ASSERT_MSG
    ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/mpl/assert.hpp:434:48: note: expanded from macro 'BOOST_MPL_ASSERT_MSG'
#define BOOST_MPL_ASSERT_MSG( c, msg, types_ ) \
                                               ^
/usr/include/boost/mpl/assert.hpp:428:9: note: expanded from macro '\
BOOST_MPL_ASSERT_MSG_IMPL'
        boost::mpl::assertion_failed<(c)>( BOOST_PP_CAT(mpl_assert_arg,counter)::assert_arg() ) \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/mpl/assert.hpp:59:58: note: expanded from macro '\
BOOST_MPL_AUX_ASSERT_CONSTANT'
#   define BOOST_MPL_AUX_ASSERT_CONSTANT(T, expr) enum { expr }
                                                         ^
/usr/include/boost/geometry/algorithms/not_implemented.hpp:105:7: note: in instantiation of template class
      'boost::geometry::nyi::not_implemented_error<boost::geometry::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING, void>' requested here
      nyi::not_implemented_error
      ^
/usr/include/boost/geometry/algorithms/equals.hpp:165:16: note: in instantiation of template class 'boost::geometry::not_implemented<boost::geometry::multi_linestring_tag,
      boost::geometry::multi_linestring_tag, void>' requested here
struct equals: not_implemented<Tag1, Tag2>
               ^
/usr/include/boost/geometry/algorithms/equals.hpp:256:16: note: in instantiation of template class
      'boost::geometry::dispatch::equals<mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_line_string<double>, boost::geometry::multi_linestring_tag,
      boost::geometry::multi_linestring_tag, 2, false>' requested here
        return equals<Geometry1, Geometry2>::apply(geometry1, geometry2);
               ^
/usr/include/boost/geometry/algorithms/equals.hpp:374:18: note: in instantiation of member function
      'boost::geometry::dispatch::devarianted_equals<mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_line_string<double> >::apply' requested here
               ::apply(geometry1, geometry2);
                 ^
test/unit/serialization/wkb_test.cpp:64:33: note: in instantiation of function template specialization 'boost::geometry::equals<mapnik::geometry::multi_line_string<double>,
      mapnik::geometry::multi_line_string<double> >' requested here
        return boost::geometry::equals(lhs, rhs);
                                ^
deps/mapbox/variant/variant.hpp:447:24: note: (skipping 4 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                return f(unwrapper<T>::apply_const(v0.template get<T>()),
                       ^
deps/mapbox/variant/variant.hpp:459:54: note: in instantiation of member function 'mapbox::util::detail::binary_dispatcher<const (anonymous namespace)::spatially_equal_visitor
      &, mapnik::geometry::geometry<double>, bool, mapnik::geometry::line_string<double>, mapnik::geometry::polygon<double, rings_container>,
      mapnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>,
      mapbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> > >::apply_const' requested here
        return binary_dispatcher<F, V, R, Types...>::apply_const(v0, v1, std::forward<F>(f));
                                                     ^
deps/mapbox/variant/variant.hpp:459:54: note: in instantiation of member function 'mapbox::util::detail::binary_dispatcher<const (anonymous namespace)::spatially_equal_visitor
      &, mapnik::geometry::geometry<double>, bool, mapnik::geometry::point<double>, mapnik::geometry::line_string<double>, mapnik::geometry::polygon<double, rings_container>,
      mapnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>,
      mapbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> > >::apply_const' requested here
        return binary_dispatcher<F, V, R, Types...>::apply_const(v0, v1, std::forward<F>(f));
                                                     ^
deps/mapbox/variant/variant.hpp:798:62: note: in instantiation of member function 'mapbox::util::detail::binary_dispatcher<const (anonymous namespace)::spatially_equal_visitor
      &, mapnik::geometry::geometry<double>, bool, mapnik::geometry::geometry_empty, mapnik::geometry::point<double>, mapnik::geometry::line_string<double>,
      mapnik::geometry::polygon<double, rings_container>, mapnik::geometry::multi_point<double>, mapnik::geometry::multi_line_string<double>,
      mapnik::geometry::multi_polygon<double>, mapbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> > >::apply_const' requested here
        return detail::binary_dispatcher<F, V, R, Types...>::apply_const(v0, v1, std::forward<F>(f));
                                                             ^
include/mapnik/util/variant.hpp:70:15: note: in instantiation of function template specialization 'mapbox::util::variant<mapnik::geometry::geometry_empty,
      mapnik::geometry::point<double>, mapnik::geometry::line_string<double>, mapnik::geometry::polygon<double, rings_container>, mapnik::geometry::multi_point<double>,
      mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_polygon<double>, mapbox::util::recursive_wrapper<mapnik::geometry::geometry_collection<double> >
      >::binary_visit<const (anonymous namespace)::spatially_equal_visitor &, mapnik::geometry::geometry<double>, bool>' requested here
    return V::binary_visit(v0, v1, std::forward<F>(f));
              ^
test/unit/serialization/wkb_test.cpp:37:32: note: in instantiation of function template specialization 'mapnik::util::apply_visitor<const
      (anonymous namespace)::spatially_equal_visitor &, mapnik::geometry::geometry<double> >' requested here
            if (!mapnik::util::apply_visitor(*this, lhs[index], rhs[index]))
                               ^
/usr/include/boost/mpl/assert.hpp:82:5: note: candidate function [with C = false] not viable: no known conversion from 'boost::mpl::failed
      ************(boost::geometry::nyi::not_implemented_error<boost::geometry::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING,
      void>::THIS_OPERATION_IS_NOT_OR_NOT_YET_IMPLEMENTED::************)(types<boost::geometry::info::MULTI_LINESTRING, boost::geometry::info::MULTI_LINESTRING, void>)' to
      'typename assert<false>::type' (aka 'mpl_::assert<false>') for 1st argument
int assertion_failed( typename assert<C>::type );
    ^
clang++ -o utils/svg2png/svg2png utils/svg2png/svg2png.o -Ldeps/agg -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/lib -L/lib64 -L/usr/lib64 -L/usr/lib/postgresql94/lib64 -lmapnik -lboost_program_options -lagg -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl
/usr/bin/ld: skipping incompatible /usr/lib/libz.so when searching for -lz
/usr/bin/ld: skipping incompatible /usr/lib/libz.a when searching for -lz
1 error generated.
scons: *** [test/unit/serialization/wkb_test.o] Error 1

```

**Comment by lightmare** [comment] 2017-02-22 17:34
Looks like a duplicate of #3380, which has been fixed.

**Closed by lightmare** 2017-02-22 17:34 UTC
